# config/routes.yaml

api_register:
  path: /api/register
  controller: App\Controller\RegisterController::register
  methods: [GET,POST]

api_login:
  path: /api/login
  controller: App\Controller\AuthController::login
  methods: [GET,POST]
api_mood_entries_create:
  path: /api/mood-entries
  controller: App\Controller\Api\MoodEntryController::create
  methods: [POST]
